### ISSUE TITLE
Template is not responsive on mobile phones

### ISSUE THREAD

**Issue by ktk** [zazuko/data.admin.ch#10] opened 2016-05-26 10:17 UTC
While I can get a responsive view in the web browser (if I make it small enough) I don't get this on my mobile phone. I tried Firefox & Chrome on Android and both just show the fixed with page.

Also in the browser the menu does not flip to the typical mobile-menu structure with a dropdown

@alemela

**Comment by alemela** [comment] 2016-06-01 15:49
I've tested also on my mobile phone and I see the same behaviour. I think the cause is on the css' "fluid" part based on pixel instead of %. So if you change browser dimension it works, also if you have very low resolution. But if you have high resolution but small screen it doesn't work.

I fix it by next Monday.

**Comment by retog** [comment] 2016-06-02 10:33
Not sure what the problem is, px is no longer tied to pixels.

On a typical Android browser things show up the same way as on a Desktop because it still readable like that and the blocks can still be shown with the required proportions. Response doesn't mean it has to look different, just that it has to look good and be easy to read. So I think the issue should be closed as it actually is responsive, and new issues should be opened if the font is considered to small or the columns to narrow.

**Closed** 2016-06-27 10:45 UTC
