### ISSUE TITLE
Content-Negotiation not working correctly (Accept-Header not intepreted correctly)

### ISSUE THREAD

**Issue by retog** [zazuko/data.admin.ch#2] opened 2018-02-14 15:50 UTC
With the accept header set to `text/turtle;q=1, application/n-triples;q=.9, application/rdf+xml;q=.8, application/ld+json;q=.7` one correctly gets a `text/turtle` response, but with `text/turtle;q=1, application/n-triples;q=.9, application/rdf+xml;q=.8, application/ld+json;q=.7, */*;q=.1` one gets `text/html`. Clearly HTML is not the best format available after a 90% mark-down in quality.

Not sure if this is an issue with trifid or with a proxy you're using.

**Comment by l00mi** [comment] 2018-02-14 21:57
Thanks for reporting, the issue is known and fixed in the latest version of trifid.

We work on upgrading all our instances currently.

**Comment by l00mi** [comment] 2018-02-15 11:48
Deployed.

**Closed as completed by l00mi** 2018-02-15 11:48 UTC
